### ISSUE TITLE
Error while creating Jenkins agent - resources are not assigned

### ISSUE THREAD

**Issue by paweloczadly** [jenkinsci/mesos-plugin#111]
Environment:
* The mesos-plugin is properly installed and configured (with default settings). 
* jenkins user is created on mesos slaves and has JAVA_HOME properly set
* jenkins-scheduler is properly registered in the mesos master ui. 
* a job is restricted to run on slaves labeled by 'mesos'
* LIBPROCESS_IP env var is set on each mesos slave

When I start my job, I can see that Jenkins agent is created:
*mesos-jenkins-aeb20d89-2d3b-4d68-9e4f-fc82e97ee4d9  (offline)*

Logs from the Jenkins slave:
```
Starting mesos slave mesos-jenkins-aeb20d89-2d3b-4d68-9e4f-fc82e97ee4d9
...
```

Jenkins config.xml content with the mesos-plugin section:
```xml
<clouds>
  <org.jenkinsci.plugins.mesos.MesosCloud plugin="mesos@0.7.0">
    <name>MesosCloud</name>
    <nativeLibraryPath>/usr/local/lib/libmesos.so</nativeLibraryPath>
    <master>pawel-mesos-master.com:5050</master>
    <description></description>
    <frameworkName>jenkins-scheduler</frameworkName>
    <slavesUser></slavesUser>
    <principal>jenkins</principal>
    <secret></secret>
    <checkpoint>false</checkpoint>
    <onDemandRegistration>false</onDemandRegistration>
    <jenkinsURL></jenkinsURL>
    <slaveInfos>
      <org.jenkinsci.plugins.mesos.MesosSlaveInfo>
        <slaveCpus>0.1</slaveCpus>
        <slaveMem>512</slaveMem>
        <executorCpus>0.1</executorCpus>
        <maxExecutors>2</maxExecutors>
        <executorMem>128</executorMem>
        <remoteFSRoot>jenkins</remoteFSRoot>
        <idleTerminationMinutes>3</idleTerminationMinutes>
        <jvmArgs>-Xms16m -XX:+UseConcMarkSweepGC -Djava.net.preferIPv4Stack=true</jvmArgs>
        <jnlpArgs></jnlpArgs>
        <labelString>mesos</labelString>
      </org.jenkinsci.plugins.mesos.MesosSlaveInfo>
    </slaveInfos>
  </org.jenkinsci.plugins.mesos.MesosCloud>
</clouds>
```
Logs from the Jenkins master:

```
Running from: /usr/share/jenkins/jenkins.war
May 27, 2015 2:54:30 PM winstone.Logger logInternal
INFO: Beginning extraction from war file
May 27, 2015 2:54:30 PM org.eclipse.jetty.util.log.JavaUtilLog info
INFO: jetty-winstone-2.8
May 27, 2015 2:54:32 PM org.eclipse.jetty.util.log.JavaUtilLog info
INFO: NO JSP Support for , did not find org.apache.jasper.servlet.JspServlet
Jenkins home directory: /var/lib/jenkins found at: EnvVars.masterEnvVars.get("JENKINS_HOME")
May 27, 2015 2:54:32 PM org.eclipse.jetty.util.log.JavaUtilLog info
INFO: Started SelectChannelConnector@0.0.0.0:8080
May 27, 2015 2:54:32 PM winstone.Logger logInternal
INFO: Winstone Servlet Engine v2.0 running: controlPort=disabled
May 27, 2015 2:54:33 PM jenkins.InitReactorRunner$1 onAttained
INFO: Started initialization
May 27, 2015 2:54:33 PM jenkins.InitReactorRunner$1 onAttained
INFO: Listed all plugins
May 27, 2015 2:54:33 PM hudson.plugins.greenballs.PluginImpl start
INFO: Green Balls!
May 27, 2015 2:54:33 PM jenkins.InitReactorRunner$1 onAttained
INFO: Prepared all plugins
May 27, 2015 2:54:33 PM jenkins.InitReactorRunner$1 onAttained
INFO: Started all plugins
May 27, 2015 2:54:33 PM jenkins.InitReactorRunner$1 onAttained
INFO: Augmented all extensions
May 27, 2015 2:54:37 PM jenkins.InitReactorRunner$1 onAttained
INFO: Loaded all jobs
May 27, 2015 2:54:37 PM hudson.model.AsyncPeriodicWork$1 run
INFO: Started Download metadata
May 27, 2015 2:54:37 PM hudson.model.AsyncPeriodicWork$1 run
INFO: Finished Download metadata. 2 ms
May 27, 2015 2:54:37 PM org.jenkinsci.plugins.mesos.MesosCloud restartMesos
INFO: Mesos master changed, restarting the scheduler
May 27, 2015 2:54:37 PM org.jenkinsci.plugins.mesos.JenkinsScheduler <init>
INFO: JenkinsScheduler instantiated with jenkins http://pawel-jenkins-master.com:8080/ and mesos pawel-mesos-master.com:5050
May 27, 2015 2:54:37 PM org.jenkinsci.plugins.mesos.JenkinsScheduler$1 run
INFO: Initializing the Mesos driver with options
Framework Name: jenkins-scheduler
Principal: jenkins
Checkpointing: false
I0527 14:54:37.527927 22162 sched.cpp:157] Version: 0.22.1
I0527 14:54:37.530427 22168 sched.cpp:254] New master detected at master@10.8.136.71:5050
I0527 14:54:37.530638 22168 sched.cpp:264] No credentials provided. Attempting to register without authentication
I0527 14:54:37.535171 22164 sched.cpp:448] Framework registered with 20150527-145223-1200097290-5050-8958-0000
May 27, 2015 2:54:37 PM org.jenkinsci.plugins.mesos.JenkinsScheduler registered
INFO: Framework registered! ID = 20150527-145223-1200097290-5050-8958-0000
May 27, 2015 2:54:37 PM org.jenkinsci.main.modules.sshd.SSHD start
INFO: Started SSHD at port 40767
May 27, 2015 2:54:37 PM jenkins.InitReactorRunner$1 onAttained
INFO: Completed initialization
May 27, 2015 2:54:37 PM hudson.WebAppMain$3 run
INFO: Jenkins is fully up and running
May 27, 2015 2:56:17 PM org.jenkinsci.plugins.mesos.MesosCloud provision
INFO: Provisioning Jenkins Slave on Mesos with 1 executors. Remaining excess workload: 0 executors)
May 27, 2015 2:56:17 PM hudson.slaves.NodeProvisioner$StandardStrategyImpl apply
INFO: Started provisioning MesosCloud from MesosCloud with 1 executors. Remaining excess workload: 0
May 27, 2015 2:56:17 PM org.jenkinsci.plugins.mesos.MesosComputerLauncher <init>
INFO: Constructing MesosComputerLauncher
May 27, 2015 2:56:17 PM org.jenkinsci.plugins.mesos.MesosSlave <init>
INFO: Constructing Mesos slave mesos-jenkins-aeb20d89-2d3b-4d68-9e4f-fc82e97ee4d9 from cloud 
May 27, 2015 2:56:27 PM org.jenkinsci.plugins.mesos.MesosComputerLauncher launch
INFO: Launching slave computer mesos-jenkins-aeb20d89-2d3b-4d68-9e4f-fc82e97ee4d9
May 27, 2015 2:56:27 PM org.jenkinsci.plugins.mesos.MesosComputerLauncher launch
INFO: Sending a request to start jenkins slave mesos-jenkins-aeb20d89-2d3b-4d68-9e4f-fc82e97ee4d9
May 27, 2015 2:56:27 PM org.jenkinsci.plugins.mesos.JenkinsScheduler requestJenkinsSlave
INFO: Enqueuing jenkins slave request
May 27, 2015 2:56:27 PM hudson.slaves.NodeProvisioner$2 run
INFO: MesosCloud provisioning successfully completed. We have now 2 computer(s)
May 27, 2015 2:56:27 PM org.jenkinsci.plugins.mesos.MesosCloud provision
INFO: Provisioning Jenkins Slave on Mesos with 1 executors. Remaining excess workload: 0 executors)
May 27, 2015 2:56:27 PM hudson.slaves.NodeProvisioner$StandardStrategyImpl apply
INFO: Started provisioning MesosCloud from MesosCloud with 1 executors. Remaining excess workload: -0.349
May 27, 2015 2:56:27 PM org.jenkinsci.plugins.mesos.MesosComputerLauncher <init>
INFO: Constructing MesosComputerLauncher
May 27, 2015 2:56:27 PM org.jenkinsci.plugins.mesos.MesosSlave <init>
INFO: Constructing Mesos slave mesos-jenkins-a01d011a-351b-4b7d-875e-562bd907eda9 from cloud 
Exception in thread "Thread-39" java.lang.NullPointerException
        at org.jenkinsci.plugins.mesos.JenkinsScheduler.matches(JenkinsScheduler.java:306)
        at org.jenkinsci.plugins.mesos.JenkinsScheduler.resourceOffers(JenkinsScheduler.java:252)
I0527 14:56:29.382058 22170 sched.cpp:1623] Asked to abort the driver
I0527 14:56:29.382205 22170 sched.cpp:856] Aborting framework '20150527-145223-1200097290-5050-8958-0000'
May 27, 2015 2:56:29 PM org.jenkinsci.plugins.mesos.JenkinsScheduler$1 run
SEVERE: The Mesos driver was aborted! Status code: 3
May 27, 2015 2:56:37 PM org.jenkinsci.plugins.mesos.MesosComputerLauncher launch
INFO: Launching slave computer mesos-jenkins-a01d011a-351b-4b7d-875e-562bd907eda9
May 27, 2015 2:56:37 PM org.jenkinsci.plugins.mesos.MesosComputerLauncher launch
WARNING: Not launching mesos-jenkins-a01d011a-351b-4b7d-875e-562bd907eda9 because the Mesos Jenkins scheduler is not running
May 27, 2015 2:56:37 PM org.jenkinsci.plugins.mesos.MesosSlave terminate
INFO: Terminating slave mesos-jenkins-a01d011a-351b-4b7d-875e-562bd907eda9
May 27, 2015 2:56:37 PM hudson.slaves.NodeProvisioner$2 run
INFO: MesosCloud provisioning successfully completed. We have now 3 computer(s)
May 27, 2015 2:56:37 PM org.jenkinsci.plugins.mesos.MesosCloud provision
INFO: Provisioning Jenkins Slave on Mesos with 1 executors. Remaining excess workload: 0 executors)
May 27, 2015 2:56:37 PM hudson.slaves.NodeProvisioner$StandardStrategyImpl apply
INFO: Started provisioning MesosCloud from MesosCloud with 1 executors. Remaining excess workload: -0.414
May 27, 2015 2:56:37 PM org.jenkinsci.plugins.mesos.MesosComputerLauncher <init>
INFO: Constructing MesosComputerLauncher
May 27, 2015 2:56:37 PM org.jenkinsci.plugins.mesos.MesosSlave <init>
INFO: Constructing Mesos slave mesos-jenkins-a9292725-2d09-47e5-9aec-016b950a5878 from cloud 
May 27, 2015 2:56:37 PM org.jenkinsci.plugins.mesos.JenkinsScheduler terminateJenkinsSlave
INFO: Terminating jenkins slave mesos-jenkins-a01d011a-351b-4b7d-875e-562bd907eda9
May 27, 2015 2:56:37 PM org.jenkinsci.plugins.mesos.JenkinsScheduler terminateJenkinsSlave
WARNING: Asked to kill unknown mesos task value: "mesos-jenkins-a01d011a-351b-4b7d-875e-562bd907eda9"
```

**Comment by paweloczadly** [comment]
One more thing, mesos-plugin 0.6.0 works fine

**Comment by geoffroyjabouley** [comment]
Hello

i am also seeing this behavior when i request more resources than the Mesos cluster can offer.

For example, if my mesos cluster has 1GB of available ram and i request a jenkins mesos slave with 2GB of ram, then i get the same NullPointerException. If i reduce the ram request to 512MB, then the slave starts fine...

This looks like a regression since v0.6.0

**Comment by geoffroyjabouley** [comment]
Seems that the line https://github.com/jenkinsci/mesos-plugin/blob/mesos-0.7.0/src/main/java/org/jenkinsci/plugins/mesos/JenkinsScheduler.java#L325 of file JenkinsScheduler.java cause the problem.

```
String requestedPorts = StringUtils.join(request.request.slaveInfo.getContainerInfo().getPortMappings().toArray(), "/");
```

I have not investigated in details, but in my case i don't declare any port mapping, so it could be possible that getPortMappings() returns a NULL reference, which would cause the NullPointerException.

I have commented this line (and also line https://github.com/jenkinsci/mesos-plugin/blob/mesos-0.7.0/src/main/java/org/jenkinsci/plugins/mesos/JenkinsScheduler.java#L334) and compiled the plugin, i do not see the NullPointerException again.

**Comment by geoffroyjabouley** [comment]
I had to update jenkins config.xml file in order to add the following xml fields to each of my mesos slaves description:

'''
<networking>HOST</networking>
<portMappings class="empty-list"/>
'''

I don't hit the nullpointer exception anymore

**Comment by maselvaraj** [comment]
Thanks everyone for triaging the issue. I haven't had time to look into it yet. I'll fix this over the weekend.
