### ISSUE TITLE
A java.lang.NullPointerException is thrown when "Docker Privileged Mode" field is not checked

### ISSUE THREAD

**Issue by jlrigau** [jenkinsci/mesos-plugin#137]
This issue is linked to https://github.com/jenkinsci/mesos-plugin/pull/123

```java
SEVERE org.jenkinsci.plugins.mesos.JenkinsScheduler resourceOffers
null
java.lang.NullPointerException
	at org.jenkinsci.plugins.mesos.JenkinsScheduler.createMesosTask(JenkinsScheduler.java:495)
	at org.jenkinsci.plugins.mesos.JenkinsScheduler.resourceOffers(JenkinsScheduler.java:261)
```

**Comment by maselvaraj** [comment]
I've merged your PR. Can you please close this issue?
