### ISSUE TITLE
Cannot add a MesosSlave node

### ISSUE THREAD

**Issue by kaysoky** [jenkinsci/mesos-plugin#176]
Plugin version: 2461ae1fdf67730201e1df3643a5aa94aa5906d8
Jenkins version: 1.565.3

## Problem
Note: The textboxes on `/jenkins/computer/createItem` are read-only.  So I had to modify the DOM to get past this form.  Or, you can modify `src/main/resources/org/jenkinsci/plugins/mesos/MesosSlave/configure-entries.jelly` with `s/readOnlyTextbox/textbox/g`.

When I try to add a MesosSlave node (via `/jenkins/computer/new`), upon clicking "save" (`/jenkins/computer/doCreateItem`) I run into this error:
```
javax.servlet.ServletException: java.lang.RuntimeException: Failed to instantiate class org.jenkinsci.plugins.mesos.MesosSlave from {"name":"asdf","numExecutors":"1","labelString":"","idleTerminationMinutes":"3","type":"org.jenkinsci.plugins.mesos.MesosSlave"}
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:783)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:863)
	at org.kohsuke.stapler.MetaClass$4.doDispatch(MetaClass.java:210)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:53)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:733)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:863)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:636)
	at org.kohsuke.stapler.Stapler.service(Stapler.java:225)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:820)
	at org.mortbay.jetty.servlet.ServletHolder.handle(ServletHolder.java:491)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1074)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:96)
	at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:88)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1065)
	at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:48)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1065)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:84)
	at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:76)
	at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:164)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1065)
	at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:46)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1065)
	at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:81)
	at org.mortbay.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1065)
	at org.mortbay.jetty.servlet.ServletHandler.handle(ServletHandler.java:365)
	at org.mortbay.jetty.security.SecurityHandler.handle(SecurityHandler.java:185)
	at org.mortbay.jetty.servlet.SessionHandler.handle(SessionHandler.java:181)
	at org.mortbay.jetty.handler.ContextHandler.handle(ContextHandler.java:689)
	at org.mortbay.jetty.webapp.WebAppContext.handle(WebAppContext.java:391)
	at org.mortbay.jetty.handler.ContextHandlerCollection.handle(ContextHandlerCollection.java:146)
	at org.mortbay.jetty.handler.HandlerCollection.handle(HandlerCollection.java:114)
	at org.mortbay.jetty.handler.HandlerWrapper.handle(HandlerWrapper.java:139)
	at org.mortbay.jetty.Server.handle(Server.java:285)
	at org.mortbay.jetty.HttpConnection.handleRequest(HttpConnection.java:457)
	at org.mortbay.jetty.HttpConnection$RequestHandler.content(HttpConnection.java:765)
	at org.mortbay.jetty.HttpParser.parseNext(HttpParser.java:628)
	at org.mortbay.jetty.HttpParser.parseAvailable(HttpParser.java:209)
	at org.mortbay.jetty.HttpConnection.handle(HttpConnection.java:357)
	at org.mortbay.io.nio.SelectChannelEndPoint.run(SelectChannelEndPoint.java:329)
	at org.mortbay.thread.BoundedThreadPool$PoolThread.run(BoundedThreadPool.java:475)
Caused by: java.lang.RuntimeException: Failed to instantiate class org.jenkinsci.plugins.mesos.MesosSlave from {"name":"asdf","numExecutors":"1","labelString":"","idleTerminationMinutes":"3","type":"org.jenkinsci.plugins.mesos.MesosSlave"}
	at hudson.model.Descriptor.newInstance(Descriptor.java:576)
	at hudson.model.ComputerSet.doDoCreateItem(ComputerSet.java:293)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:497)
	at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:298)
	at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:161)
	at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:96)
	at org.kohsuke.stapler.MetaClass$1.doDispatch(MetaClass.java:120)
	at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:53)
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:733)
	... 39 more
Caused by: java.lang.IllegalArgumentException: Failed to instantiate class org.jenkinsci.plugins.mesos.MesosSlave from {"name":"asdf","numExecutors":"1","labelString":"","idleTerminationMinutes":"3","type":"org.jenkinsci.plugins.mesos.MesosSlave"}
	at org.kohsuke.stapler.RequestImpl$TypePair.convertJSON(RequestImpl.java:589)
	at org.kohsuke.stapler.RequestImpl.bindJSON(RequestImpl.java:400)
	at org.kohsuke.stapler.RequestImpl.bindJSON(RequestImpl.java:396)
	at hudson.model.Descriptor.newInstance(Descriptor.java:567)
	... 50 more
Caused by: org.kohsuke.stapler.NoStaplerConstructorException: There's no @DataBoundConstructor on any constructor of class org.jenkinsci.plugins.mesos.MesosSlave
	at org.kohsuke.stapler.ClassDescriptor.loadConstructorParamNames(ClassDescriptor.java:177)
	at org.kohsuke.stapler.RequestImpl.instantiate(RequestImpl.java:671)
	at org.kohsuke.stapler.RequestImpl.access$100(RequestImpl.java:81)
	at org.kohsuke.stapler.RequestImpl$TypePair.convertJSON(RequestImpl.java:587)
	... 53 more
```

## To repro:
```
mvn package
mvn hpi:run
```
1. Click "Build Executor Status" on the left navigation panel.
1. Click "New Node", on the left.
1. Enter a node name.
1. Select "Mesos Slave".
1. Enter a number of executors.
  1. Right click on the "# of executors" text box and inspect the element.  
  1. Manually append `value="2"` to the element.
1. Click "Save".

**Comment by vinodkone** [comment]
Manually adding a mesos slave/agent node is not supported. The plugin automatically adds/removes agents based on load.
