### ISSUE TITLE
Metrics Plugin added as Dependency

### ISSUE THREAD

**Issue by ianpward** [jenkinsci/mesos-plugin#223]
In following the installation instructions on the readme we ran into the following error in the Jenkins logs after configuring the Mesos plugin:

```Failed to scout org.jenkinsci.plugins.mesos.MesosHealthCheckProvider
java.lang.InstantiationException: java.lang.NoClassDefFoundError: jenkins/metrics/api/HealthCheckProvider
        at net.java.sezpoz.IndexItem.element(IndexItem.java:146)
        at hudson.ExtensionFinder$Sezpoz.scout(ExtensionFinder.java:662)
        at hudson.ClassicPluginStrategy.findComponents(ClassicPluginStrategy.java:383)
        at hudson.ExtensionList.load(ExtensionList.java:349)
        at hudson.ExtensionList.ensureLoaded(ExtensionList.java:287)
        at hudson.ExtensionList.iterator(ExtensionList.java:156)
        at hudson.ClassicPluginStrategy.findComponents(ClassicPluginStrategy.java:382)
        at hudson.ExtensionList.load(ExtensionList.java:349)
        at hudson.ExtensionList.ensureLoaded(ExtensionList.java:287)
        at hudson.ExtensionList.get(ExtensionList.java:171)
        at hudson.PluginManager$PluginUpdateMonitor.getInstance(PluginManager.java:1347)
        at hudson.maven.PluginImpl.init(PluginImpl.java:58)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at hudson.init.TaskMethodFinder.invoke(TaskMethodFinder.java:106)
        at hudson.init.TaskMethodFinder$TaskImpl.run(TaskMethodFinder.java:175)
        at org.jvnet.hudson.reactor.Reactor.runTask(Reactor.java:282)
        at jenkins.model.Jenkins$8.runTask(Jenkins.java:958)
        at org.jvnet.hudson.reactor.Reactor$2.run(Reactor.java:210)
        at org.jvnet.hudson.reactor.Reactor$Node.run(Reactor.java:117)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.NoClassDefFoundError: jenkins/metrics/api/HealthCheckProvider
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:760)
        at jenkins.util.AntClassLoader.defineClassFromData(AntClassLoader.java:1139)
        at hudson.ClassicPluginStrategy$AntClassLoader2.defineClassFromData(ClassicPluginStrategy.java:802)
        at jenkins.util.AntClassLoader.getClassFromStream(AntClassLoader.java:1310)
        at jenkins.util.AntClassLoader.findClassInComponents(AntClassLoader.java:1366)
        at jenkins.util.AntClassLoader.findClass(AntClassLoader.java:1326)
        at sun.reflect.GeneratedMethodAccessor5.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:497)
        at jenkins.ClassLoaderReflectionToolkit.invoke(ClassLoaderReflectionToolkit.java:44)
        at jenkins.ClassLoaderReflectionToolkit._findClass(ClassLoaderReflectionToolkit.java:86)
        at hudson.PluginManager$UberClassLoader.findClass(PluginManager.java:1209)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:424)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        at net.java.sezpoz.IndexItem.element(IndexItem.java:134)
        ... 24 more
Caused by: java.lang.ClassNotFoundException: jenkins.metrics.api.HealthCheckProvider
        at jenkins.util.AntClassLoader.findClassInComponents(AntClassLoader.java:1376)
        at jenkins.util.AntClassLoader.findClass(AntClassLoader.java:1326)
        at jenkins.util.AntClassLoader.loadClass(AntClassLoader.java:1079)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
        ... 40 more```

the MesosHealthCheckProvider class is part of the Metrics plugin here:
https://wiki.jenkins-ci.org/display/JENKINS/Metrics+Plugin

This should be loaded as a dependency for the Mesos Plugin. Once loaded the errors cease. 

Additionally, under `Configuring the plugin,` the instructions should indicate that the `On-demand framework registration` option under the Advanced Configuration button should be toggled from the default so that the framework shows registered in the Mesos UI. This does not happen by default unless a build is scheduled in Jenkins.

**Comment by Vlatombe** [comment]
Note that this isn't an error as such. This is just the way Jenkins reacts when optional dependencies are not present. Not having the metrics plugin installed will not prevent any usual usage of the mesos plugin, it will just disable the specific MesosHealthCheckProvider. Nevertheless, I'll add an optional step to the instructions
