### ISSUE TITLE
Node Properties feature will break connection to slaves when saving config.

### ISSUE THREAD

**Issue by eThomasHerrlin** [jenkinsci/mesos-plugin#227]
When "Node Properties" feature is active and I am clicking apply/save on manage jenkins config, then it will break connection to all running mesos builds.
This happen even if I have done no config changes.
If there are no node propertiy items added, then the bug will not be triggered.

If this is a feature to ensure that all mesos nodes have the updated node config, then it should only trigger restart if the config actually have been changed.
My expectation is also that node restart should be done gracefully. Perhaps mark running mesos nodes as offline to allow running jobs to finish.

Environment:
	Jenkins 1.642.4
	Mesos plugin 0.12.0
	Checkpointing: yes
	On-demand framework registration: yes
	Decline offer duration: 5000
	Idle termination: 1

Node Properties -> Environment variables item added. With or without any key pairs defined.

Output from simple "sleep 3600" mesos job running while clicking apply in jenkins/manage/configure system:
`
Slave went offline during the build
ERROR: Connection was broken: java.io.IOException: Connection aborted: org.jenkinsci.remoting.nio.NioChannelHub$MonoNioTransport@761bea6c[name=mesos-jenkins-0ea5c94507414248ba85e56f8f41a61a-Linux_redhat]
	at org.jenkinsci.remoting.nio.NioChannelHub$NioTransport.abort(NioChannelHub.java:208)
	at org.jenkinsci.remoting.nio.NioChannelHub.run(NioChannelHub.java:628)
	at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Connection reset by peer
	at sun.nio.ch.FileDispatcherImpl.read0(Native Method)
	at sun.nio.ch.SocketDispatcher.read(SocketDispatcher.java:39)
	at sun.nio.ch.IOUtil.readIntoNativeBuffer(IOUtil.java:223)
	at sun.nio.ch.IOUtil.read(IOUtil.java:197)
	at sun.nio.ch.SocketChannelImpl.read(SocketChannelImpl.java:380)
	at org.jenkinsci.remoting.nio.FifoBuffer$Pointer.receive(FifoBuffer.java:136)
	at org.jenkinsci.remoting.nio.FifoBuffer.receive(FifoBuffer.java:306)
	at org.jenkinsci.remoting.nio.NioChannelHub.run(NioChannelHub.java:561)
	... 6 more
`

**Comment by Vlatombe** [comment]
Indeed, NodeProperties doesn't implement #equals method :/. As you suggest, we should implement a graceful restart, by draining the framework instead of killing the nodes.

**Comment by Vlatombe** [comment]
Fixed through #246
