### ISSUE TITLE
NullPointer after upgrade to 0.13.0

### ISSUE THREAD

**Issue by h0tbird** [jenkinsci/mesos-plugin#249]
```
Timer task hudson.model.LoadStatistics$LoadStatisticsUpdater@69c1fef7 failed
java.lang.NullPointerException
	at org.jenkinsci.plugins.mesos.MesosSlaveInfo.matchesLabel(MesosSlaveInfo.java:380)
	at org.jenkinsci.plugins.mesos.MesosCloud.canProvision(MesosCloud.java:463)
	at hudson.model.Label.getClouds(Label.java:227)
	at hudson.model.Label.isEmpty(Label.java:435)
	at jenkins.model.Jenkins.getLabels(Jenkins.java:1755)
	at hudson.model.LoadStatistics$LoadStatisticsUpdater.doRun(LoadStatistics.java:396)
	at hudson.triggers.SafeTimerTask.run(SafeTimerTask.java:50)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
	at java.util.concurrent.FutureTask.runAndReset(FutureTask.java:304)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.access$301(ScheduledThreadPoolExecutor.java:178)
	at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:293)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
	at java.lang.Thread.run(Thread.java:745)
```

**Comment by Vlatombe** [comment]
Thanks for your report. It is now fixed on master. As a workaround, you can go to the global Jenkins configuration then save.

**Comment by h0tbird** [comment]
The workaround works for me. Thx!
