### ISSUE TITLE
Builds fail with a "no longer a configured node for ..."

### ISSUE THREAD

**Issue by damomurf** [jenkinsci/mesos-plugin#256]
We're frequently seeing random jobs die mid-execution with an error similar to that below:

```
FATAL: no longer a configured node for mesos-jenkins-7ee5baea37ef44868bfe4a3fe98ccfbd-mesos-java8
 java.lang.IllegalStateException: no longer a configured node for mesos-jenkins-7ee5baea37ef44868bfe4a3fe98ccfbd-mesos-java8
    at hudson.model.AbstractBuild$AbstractBuildExecution.getCurrentNode(AbstractBuild.java:453)
    at hudson.model.AbstractBuild$AbstractBuildExecution.reportBrokenChannel(AbstractBuild.java:810)
    at hudson.model.AbstractBuild$AbstractBuildExecution.perform(AbstractBuild.java:785)
    at hudson.model.Build$BuildExecution.build(Build.java:205)
    at hudson.model.Build$BuildExecution.doRun(Build.java:162)
    at hudson.model.AbstractBuild$AbstractBuildExecution.run(AbstractBuild.java:534)
    at hudson.model.Run.execute(Run.java:1738)
    at hudson.model.FreeStyleBuild.run(FreeStyleBuild.java:43)
    at hudson.model.ResourceController.execute(ResourceController.java:98)
    at hudson.model.Executor.run(Executor.java:410)
```

Container sandbox output, etc. simply suggests the slave was terminated normally, almost as if it reached its maximum idle timeout (currently 1 minute in our environment).

**Comment by damomurf** [comment]
This is affecting Jenkins 1.651.3 with mesos-plugin version 0.13.1.

**Comment by xiajidexue** [comment]
encountered the same problem

**Comment by xiajidexue** [comment]
who else can give a solution  or workaround for this problem? i encountered almost everyday during jenkins builds

**Comment by jeschkies** [comment]
@xiajidexue and @damomurf, do you still have the issue with 1.0 or 2.0?

**Comment by jeschkies** [comment]
Closing for lack of response.

**Comment by saiparty** [comment]
@jeschkies We are still seeing the issue in Jenkins: 1.651 and mesos plugin: 0.12.0. If the issue is fixed a reference to the patch is much appreciated!
