### ISSUE TITLE
Race condition in slave deletion causes https://issues.jenkins-ci.org/browse/JENKINS-24050

### ISSUE THREAD

**Issue by maselvaraj** [jenkinsci/mesos-plugin#282]
Jan 30, 2017 8:04:54 AM org.jenkinsci.plugins.mesos.JenkinsScheduler terminateJenkinsSlave
INFO: Terminating jenkins slave mesos-jenkins-bd9e7e6dc2fd4f20bc5fcfa43f727266-mesos
Jan 30, 2017 8:04:54 AM org.jenkinsci.plugins.mesos.JenkinsScheduler terminateJenkinsSlave
INFO: Killing mesos task value: "mesos-jenkins-bd9e7e6dc2fd4f20bc5fcfa43f727266-mesos"

Jan 30, 2017 8:04:54 AM org.jenkinsci.plugins.mesos.MesosComputer deleteSlave
INFO: Terminating mesos-jenkins-bd9e7e6dc2fd4f20bc5fcfa43f727266-mesos slave
Jan 30, 2017 8:05:16 AM org.jenkinsci.plugins.mesos.MesosRetentionStrategy checkInternal
INFO: Disconnecting idle computer mesos-jenkins-12224af43af048c890fb8483e68aeae8-mesos
Jan 30, 2017 8:05:16 AM org.jenkinsci.plugins.mesos.MesosRetentionStrategy checkInternal
INFO: Disconnecting idle computer **mesos-jenkins-b6e1d3677cdc4045a6960a35bd1de05e-mesos**
Jan 30, 2017 8:05:54 AM org.jenkinsci.plugins.mesos.MesosCleanupThread execute
INFO: Marked mesos-jenkins-12224af43af048c890fb8483e68aeae8-mesos for deletion
Jan 30, 2017 8:05:54 AM org.jenkinsci.plugins.mesos.MesosCleanupThread execute
INFO: Marked **mesos-jenkins-b6e1d3677cdc4045a6960a35bd1de05e-mesos** for deletion
Jan 30, 2017 8:05:54 AM org.jenkinsci.plugins.mesos.MesosCleanupThread$1 run
INFO: Deleting pending node mesos-jenkins-12224af43af048c890fb8483e68aeae8-mesos
Jan 30, 2017 8:05:54 AM org.jenkinsci.plugins.mesos.MesosCleanupThread$1 run
INFO: Deleting pending node **mesos-jenkins-b6e1d3677cdc4045a6960a35bd1de05e-mesos**
Jan 30, 2017 8:05:54 AM org.jenkinsci.plugins.mesos.MesosSlave terminate
INFO: Terminating slave mesos-jenkins-12224af43af048c890fb8483e68aeae8-mesos
Jan 30, 2017 8:05:54 AM org.jenkinsci.plugins.mesos.MesosSlave terminate
INFO: Terminating slave **mesos-jenkins-b6e1d3677cdc4045a6960a35bd1de05e-mesos**
Jan 30, 2017 8:05:54 AM org.jenkinsci.plugins.mesos.MesosRetentionStrategy checkInternal
INFO: Disconnecting idle computer mesos-jenkins-de6f996dea2047c7a25ed7f9feeb1b3b-mesos
Jan 30, 2017 8:05:54 AM hudson.remoting.AbstractByteArrayCommandTransport$1 handle
WARNING: Failed to construct Command
java.io.EOFException
        at java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2353)
        at java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:2822)
        at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:804)
        at java.io.ObjectInputStream.<init>(ObjectInputStream.java:301)
        at hudson.remoting.ObjectInputStreamEx.<init>(ObjectInputStreamEx.java:40)
        at hudson.remoting.AbstractByteArrayCommandTransport$1.handle(AbstractByteArrayCommandTransport.java:61)
        at org.jenkinsci.remoting.nio.NioChannelHub$2.run(NioChannelHub.java:547)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:111)
        at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)

Jan 30, 2017 8:05:54 AM org.jenkinsci.plugins.mesos.MesosRetentionStrategy checkInternal
INFO: Disconnecting idle computer **mesos-jenkins-b6e1d3677cdc4045a6960a35bd1de05e-mesos**
Jan 30, 2017 8:05:54 AM jenkins.slaves.JnlpSlaveAgentProtocol$Handler$1 onClosed
WARNING: NioChannelHub keys=4 gen=391214: Computer.threadPoolForRemoting [#4] for + mesos-jenkins-de6f996dea2047c7a25ed7f9feeb1b3b-mesos terminated
java.io.IOException: Failed to abort
        at org.jenkinsci.remoting.nio.NioChannelHub$NioTransport.abort(NioChannelHub.java:195)
        at org.jenkinsci.remoting.nio.NioChannelHub.abortAll(NioChannelHub.java:618)
        at org.jenkinsci.remoting.nio.NioChannelHub.run(NioChannelHub.java:592)
        at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.nio.channels.CancelledKeyException
        at sun.nio.ch.SelectionKeyImpl.ensureValid(SelectionKeyImpl.java:73)
        at sun.nio.ch.SelectionKeyImpl.readyOps(SelectionKeyImpl.java:87)
        at java.nio.channels.SelectionKey.isReadable(SelectionKey.java:289)
        at org.jenkinsci.remoting.nio.NioChannelHub.run(NioChannelHub.java:513)
        ... 6 more

Jan 30, 2017 8:05:54 AM jenkins.slaves.JnlpSlaveAgentProtocol$Handler$1 onClosed
WARNING: NioChannelHub keys=4 gen=391214: Computer.threadPoolForRemoting [#4] for + mesos-jenkins-3cdf97c75d6548b1b9bda2edc7e975b6-mesos terminated
java.io.IOException: Failed to abort
        at org.jenkinsci.remoting.nio.NioChannelHub$NioTransport.abort(NioChannelHub.java:195)
        at org.jenkinsci.remoting.nio.NioChannelHub.abortAll(NioChannelHub.java:618)
        at org.jenkinsci.remoting.nio.NioChannelHub.run(NioChannelHub.java:592)
        at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
/mesos-jenkins-de6f996dea2047c7a25ed7f9feeb1b3b-mesos

**Comment by maselvaraj** [comment]
Jenkins version: 1.570

mesos-jenkins-b6e1d3677cdc4045a6960a35bd1de05e-mesos is already marked for deletion by org.jenkinsci.plugins.mesos.MesosRetentionStrategy and org.jenkinsci.plugins.mesos.MesosCleanupThread has started cleanup. But org.jenkinsci.plugins.mesos.MesosRetentionStrategy once again checks the slave if it needs to be deleted which accesses the channel causing JENKINS-24050
