### ISSUE TITLE
Jenkins throws exceptions when trying to show configuration for a Mesos Agent

### ISSUE THREAD

**Issue by awltux** [jenkinsci/mesos-plugin#407]
The implementation for Mesos Agent configuration seems to be broken.
When a Mesos Agent Configuration is selected from the Agent list, Jenkins displays an error page.
Jenkins system logs show that an exception is thrown:

`Caught exception evaluating: instance.descriptor in /computer/jenkins-agent-mesos-bd0b5ee2-fe21-43bf-a50c-d5f124a4d313/configure. Reason: java.lang.reflect.InvocationTargetException
java.lang.AssertionError: class org.jenkinsci.plugins.mesos.MesosJenkinsAgent is missing its descriptor
	at jenkins.model.Jenkins.getDescriptorOrDie(Jenkins.java:1600)
	at hudson.model.Slave.getDescriptor(Slave.java:572)
Caused: java.lang.reflect.InvocationTargetException`

A basic fix is relatively simple to implement. I'll submit a pull request later today.

**Comment by awltux** [comment]
Fix has been merged into master. 
Closing.
