### ISSUE TITLE
Error while creating slaves

### ISSUE THREAD

**Issue by ktf** [jenkinsci/mesos-plugin#43]
Hi,

I've a working mesos + jenkins setup. I can execute mesos jobs just fine most of the time.

However every now and then it looks like something happens in the jenkins plugin and it cannot create new slaves on demand anymore. Looking at the logs I see a few:

```

Jun 12, 2014 9:50:51 AM hudson.remoting.AbstractByteArrayCommandTransport$1 handle
WARNING: Failed to construct Command
java.io.EOFException
        at java.io.ObjectInputStream$PeekInputStream.readFully(ObjectInputStream.java:2325)
        at java.io.ObjectInputStream$BlockDataInputStream.readShort(ObjectInputStream.java:2794)
        at java.io.ObjectInputStream.readStreamHeader(ObjectInputStream.java:801)
        at java.io.ObjectInputStream.<init>(ObjectInputStream.java:299)
        at hudson.remoting.ObjectInputStreamEx.<init>(ObjectInputStreamEx.java:40)
        at hudson.remoting.AbstractByteArrayCommandTransport$1.handle(AbstractByteArrayCommandTransport.java:61)
        at org.jenkinsci.remoting.nio.NioChannelHub$2.run(NioChannelHub.java:529)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at hudson.remoting.SingleLaneExecutorService$1.run(SingleLaneExecutorService.java:111)
        at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

Jun 12, 2014 9:50:51 AM org.jenkinsci.remoting.nio.NioChannelHub run
WARNING: Failed to select
java.nio.channels.ClosedChannelException
        at sun.nio.ch.SocketChannelImpl.shutdownInput(SocketChannelImpl.java:802)
        at sun.nio.ch.SocketAdaptor.shutdownInput(SocketAdaptor.java:426)
        at org.jenkinsci.remoting.nio.Closeables$1.close(Closeables.java:20)
        at org.jenkinsci.remoting.nio.NioChannelHub$MonoNioTransport.closeR(NioChannelHub.java:289)
        at org.jenkinsci.remoting.nio.NioChannelHub$NioTransport$1.call(NioChannelHub.java:226)
        at org.jenkinsci.remoting.nio.NioChannelHub$NioTransport$1.call(NioChannelHub.java:224)
        at org.jenkinsci.remoting.nio.NioChannelHub.run(NioChannelHub.java:474)
        at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:471)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)

Jun 12, 2014 9:50:51 AM jenkins.slaves.JnlpSlaveAgentProtocol$Handler$1 onClosed
```

and at some point I get:

```
INFO: Status update: task value: "mesos-jenkins-935484f7-14aa-4715-a4b0-c3b83040586d"
 is in state TASK_RUNNING
java.lang.IllegalStateException: Unknown taskId: value: "mesos-jenkins-935484f7-14aa-4715-a4b0-c3b83040586d"

        at org.jenkinsci.plugins.mesos.JenkinsScheduler.statusUpdate(JenkinsScheduler.java:353)
```

and the only solution is to restart the jenkins instance. Notice that running `mesos-execute` by hand still works. Ideas? I'm using 0.18.2 on RHEL6.

**Comment by sedninja** [comment]
I am seeing the same symptoms as described in this old bug report with the latest version of the jenkins-mesos plugin (0.13.1) with mesos v1.0.1 and jenkins v2.7.4. I don't get the same stack traces but the unknown task id log bits along with ultimately the jenkins framework deregistering from mesos and being unable to create any new slaves for builds.

**Comment by damomurf** [comment]
I'm having exactly the same issues as @sedninja: Jenkins 1.651.3 Mesos 1.1.0 and 0.13.1 (and also a self-built 0.13.1 with the mesos library dependency increased to 1.1.0).

**Comment by chr0n1x** [comment]
bump. Seeing this with version 0.14 of the plugin, mesos 1.0.1 - that's the version of my running cluster and the installed native lib.

@maselvaraj
