### ISSUE TITLE
cannot connect to mesos master after configuring Jenkins

### ISSUE THREAD

**Issue by scivm** [jenkinsci/mesos-plugin#6]
Hi,

I am pretty excited to try this out, but I am unable to make a connection to mesos master after configuring Jenkins.

Mesos native library path: /usr/local/lib/libmesos.so
Mesos Master [hostname:port]: xxxxx:5050

Select "Test Connection" and get the stack trace below

Mesos version: mesos_0.15.0-rc4_amd64.deb
Jenkins Version: latest

Stack trace

javax.servlet.ServletException: java.lang.NullPointerException
    at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:778)
    at org.kohsuke.stapler.Stapler.invoke(Stapler.java:858)
    at org.kohsuke.stapler.MetaClass$6.doDispatch(MetaClass.java:248)
    at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:53)
    at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:728)
    at org.kohsuke.stapler.Stapler.invoke(Stapler.java:858)
    at org.kohsuke.stapler.Stapler.invoke(Stapler.java:631)
    at org.kohsuke.stapler.Stapler.service(Stapler.java:225)
    at javax.servlet.http.HttpServlet.service(HttpServlet.java:728)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:305)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
    at org.apache.tomcat.websocket.server.WsFilter.doFilter(WsFilter.java:51)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
    at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:96)
    at hudson.plugins.greenballs.GreenBallFilter.doFilter(GreenBallFilter.java:58)
    at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:99)
    at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:88)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
    at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:48)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
    at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:84)
    at hudson.security.UnwrapSecurityExceptionFilter.doFilter(UnwrapSecurityExceptionFilter.java:51)
    at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
    at jenkins.security.ExceptionTranslationFilter.doFilter(ExceptionTranslationFilter.java:117)
    at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
    at org.acegisecurity.providers.anonymous.AnonymousProcessingFilter.doFilter(AnonymousProcessingFilter.java:125)
    at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
    at org.acegisecurity.ui.rememberme.RememberMeProcessingFilter.doFilter(RememberMeProcessingFilter.java:142)
    at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
    at org.acegisecurity.ui.AbstractProcessingFilter.doFilter(AbstractProcessingFilter.java:271)
    at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
    at org.acegisecurity.ui.basicauth.BasicProcessingFilter.doFilter(BasicProcessingFilter.java:174)
    at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
    at jenkins.security.ApiTokenFilter.doFilter(ApiTokenFilter.java:64)
    at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
    at org.acegisecurity.context.HttpSessionContextIntegrationFilter.doFilter(HttpSessionContextIntegrationFilter.java:249)
    at hudson.security.HttpSessionContextIntegrationFilter2.doFilter(HttpSessionContextIntegrationFilter2.java:67)
    at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:87)
    at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:76)
    at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:164)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
    at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:46)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
    at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:81)
    at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:243)
    at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:210)
    at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:222)
    at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:123)
    at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502)
    at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:171)
    at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:100)
    at org.apache.catalina.valves.AccessLogValve.invoke(AccessLogValve.java:953)
    at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:118)
    at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:408)
    at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1041)
    at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:603)
    at org.apache.tomcat.util.net.JIoEndpoint$SocketProcessor.run(JIoEndpoint.java:310)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
    at java.lang.Thread.run(Thread.java:744)
Caused by: java.lang.NullPointerException
    at org.jenkinsci.plugins.mesos.MesosCloud$DescriptorImpl.doTestConnection(MesosCloud.java:232)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at org.kohsuke.stapler.Function$InstanceFunction.invoke(Function.java:298)
    at org.kohsuke.stapler.Function.bindAndInvoke(Function.java:161)
    at org.kohsuke.stapler.Function.bindAndInvokeAndServeResponse(Function.java:96)
    at org.kohsuke.stapler.MetaClass$1.doDispatch(MetaClass.java:120)
    at org.kohsuke.stapler.NameBasedDispatcher.dispatch(NameBasedDispatcher.java:53)
    at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:728)
    ... 64 more
Page generated: Dec 27, 2013 6:37:43 PMREST APIJenkins ver. 1.544
Delete cloud
Add a new cloud

Mike

**Comment by ravinder1985** [comment]
What does following error means?

Stack trace

javax.servlet.ServletException: java.lang.UnsatisfiedLinkError: no mesos in java.library.path
	at org.kohsuke.stapler.Stapler.tryInvoke(Stapler.java:796)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:876)
	at org.kohsuke.stapler.Stapler.invoke(Stapler.java:649)
	at org.kohsuke.stapler.Stapler.service(Stapler.java:238)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:848)
	at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:686)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1494)
	at hudson.util.PluginServletFilter$1.doFilter(PluginServletFilter.java:132)
	at hudson.util.PluginServletFilter.doFilter(PluginServletFilter.java:123)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
	at hudson.security.csrf.CrumbFilter.doFilter(CrumbFilter.java:49)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
	at hudson.security.ChainedServletFilter$1.doFilter(ChainedServletFilter.java:84)
	at hudson.security.ChainedServletFilter.doFilter(ChainedServletFilter.java:76)
	at hudson.security.HudsonFilter.doFilter(HudsonFilter.java:171)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
	at org.kohsuke.stapler.compression.CompressionFilter.doFilter(CompressionFilter.java:49)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
	at hudson.util.CharacterEncodingFilter.doFilter(CharacterEncodingFilter.java:81)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1482)
	at org.kohsuke.stapler.DiagnosticThreadNameFilter.doFilter(DiagnosticThreadNameFilter.java:30)
	at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1474)
	at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:499)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
	at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:533)
	at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
	at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1086)
	at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:428)
	at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
	at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1020)
	at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
	at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
	at org.eclipse.jetty.server.Server.handle(Server.java:370)
	at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:489)
	at org.eclipse.jetty.server.AbstractHttpConnection.content(AbstractHttpConnection.java:960)
	at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.content(AbstractHttpConnection.java:1021)
	at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:865)
	at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:240)
	at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:668)
	at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
	at winstone.BoundedExecutorService$1.run(BoundedExecutorService.java:77)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.lang.UnsatisfiedLinkError: no mesos in java.library.path

**Comment by vinodkone** [comment]
This means the path you provided for libmesos.so (or libmesos.dylib if on osx) is incorrect.

**Comment by ravinder1985** [comment]
You mean jenkins server supposed to be on same box as mesos master?

**Comment by vinodkone** [comment]
not mesos master. mesos library (libmesos.so) that the jenkins mesos plugin uses. typically you get libmesos by installing mesos package.

**Comment by ravinder1985** [comment]
where to download mesos package? i am kinda new in this. tying to create dynamic build slaves.

**Comment by rasputnik** [comment]
@ravinder1985 you need a shared library on any mesos client - which in this case is the jenkins master.
 check your system packages for a mesos RPM/DEB, or compile your own. 

mesosphere provide apt and RPM repositories , I can't find the link right now but if you Google they'll turn up.

**Comment by ravinder1985** [comment]
its working now. Thanks a lot guys. only issue left is my mesos master couldn't start slave.
i believe because i don't have jenkins user running there. i am still investigating.

**Comment by ravinder1985** [comment]
It is able to connect to master but i am having following issue.

Logs from slave:


W1027 20:23:45.965175 30147 master.hpp:1532] Master attempted to send message to disconnected framework ad7d2cf4-5b24-4645-bac1-cf56a2712ff8-0390 (Jenkins Scheduler) at scheduler-4a1c527c-8015-4dc1-a606-ab6ee1c3abfe@96.119.2.253:59256
W1027 20:23:45.965875 30147 master.hpp:1532] Master attempted to send message to disconnected framework ad7d2cf4-5b24-4645-bac1-cf56a2712ff8-0390 (Jenkins Scheduler) at scheduler-4a1c527c-8015-4dc1-a606-ab6ee1c3abfe@96.119.2.253:59256
I1027 20:23:45.966071 30147 master.cpp:1143] Giving framework ad7d2cf4-5b24-4645-bac1-cf56a2712ff8-0390 (Jenkins Scheduler) at scheduler-4a1c527c-8015-4dc1-a606-ab6ee1c3abfe@96.119.2.253:59256 0ns to failover
I1027 20:23:45.966191 30147 hierarchical.hpp:599] Deactivated framework ad7d2cf4-5b24-4645-bac1-cf56a2712ff8-0390
I1027 20:23:45.966313 30147 hierarchical.hpp:1103] Recovered cpus(*):1; mem(*):244; disk(*):14972; ports(*):[31000-32000] (total: cpus(*):1; mem(*):244; disk(*):14972; ports(*):[31000-32000], allocated: ) on slave df5d0974-8a3c-4d65-9d36-c2c22fd035b1-S1 from framework ad7d2cf4-5b24-4645-bac1-cf56a2712ff8-0390
I1027 20:23:45.966473 30147 hierarchical.hpp:1103] Recovered cpus(*):0.9; mem(*):228; disk(*):14972; ports(*):[31000-31341, 31343-32000] (total: cpus(*):1; mem(*):244; disk(*):14972; ports(*):[31000-32000], allocated: cpus(*):0.1; mem(*):16; ports(*):[31342-31342]) on slave e932fe20-f34c-4dcc-a7f4-b9ddcc217ff9-S0 from framework ad7d2cf4-5b24-4645-bac1-cf56a2712ff8-0390
I1027 20:23:45.974308 30147 master.cpp:4815] Framework failover timeout, removing framework ad7d2cf4-5b24-4645-bac1-cf56a2712ff8-0390 (Jenkins Scheduler) at scheduler-4a1c527c-8015-4dc1-a606-ab6ee1c3abfe@96.119.2.253:59256
I1027 20:23:45.974344 30147 master.cpp:5571] Removing framework ad7d2cf4-5b24-4645-bac1-cf56a2712ff8-0390 (Jenkins Scheduler) at scheduler-4a1c527c-8015-4dc1-a606-ab6ee1c3abfe@96.119.2.253:59256
I1027 20:23:45.974576 30147 hierarchical.hpp:552] Removed framework ad7d2cf4-5b24-4645-bac1-cf56a2712ff8-0390
I1027 20:23:46.461467 30147 master.cpp:2179] Received SUBSCRIBE call for framework 'Jenkins Scheduler' at scheduler-4a1c527c-8015-4dc1-a606-ab6ee1c3abfe@96.119.2.253:59256
I1027 20:23:46.461665 30147 master.cpp:2250] Subscribing framework Jenkins Scheduler with checkpointing disabled and capabilities [  ]
I1027 20:23:46.462273 30147 hierarchical.hpp:515] Added framework ad7d2cf4-5b24-4645-bac1-cf56a2712ff8-0391
I1027 20:23:46.463017 30147 master.cpp:4967] Sending 2 offers to framework ad7d2cf4-5b24-4645-bac1-cf56a2712ff8-0391 (Jenkins Scheduler) at scheduler-4a1c527c-8015-4dc1-a606-ab6ee1c3abfe@96.119.2.253:59256


also 

W1027 20:12:33.288890 22887 slave.cpp:1995] Cannot shut down unknown framework ad7d2cf4-5b24-4645-bac1-cf56a2712ff8-0171
I1027 20:12:36.314723 22887 slave.cpp:1980] Asked to shut down framework ad7d2cf4-5b24-4645-bac1-cf56a2712ff8-0172 by master@96.119.242.62:5050
W1027 20:12:36.314999 22887 slave.cpp:1995] Cannot shut down unknown framework ad7d2cf4-5b24-4645-bac1-cf56a2712ff8-0172
I1027 20:12:39.347779 22887 slave.cpp:1980] Asked to shut down framework ad7d2cf4-5b24-4645-bac1-cf56a2712ff8-0173 by master@96.119.242.62:5050
W1027 20:12:39.347932 22887 slave.cpp:1995] Cannot shut down unknown framework ad7d2cf4-5b24-4645-bac1-cf56a2712ff8-0173


MASTER : 

master:
ct 27 19:47:42 testmesosmas-cmce-01 marathon[24375]: [2015-10-27 19:47:42,964] INFO 10.36.123.233 - - [27/Oct/2015:19:47:42 +0000] "GET //96.119.247.56:8080/v2/apps HTTP/1.1" 200 1458 "http://96.119.247.56:8080/ui/" "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_2) AppleWebKit/600.4.10 (KHTML, like Gecko) Version/8.0.4 Safari/600.4.10 (mesosphere.chaos.http.ChaosRequestLog$$EnhancerByGuice$$284a2e90:14)
Oct 27 19:47:43 testmesosmas-cmce-01 mesos-master[4231]: E1027 19:47:43.348151  4251 socket.hpp:174] Shutdown failed on fd=24: Transport endpoint is not connected [107]
Oct 27 19:47:43 testmesosmas-cmce-01 mesos-master[4231]: E1027 19:47:43.348683  4251 socket.hpp:174] Shutdown failed on fd=44: Transport endpoint is not connected [107]
Oct 27 19:47:43 testmesosmas-cmce-01 mesos-master[4231]: I1027 19:47:43.348780  4243 master.cpp:1119] Framework 2120f1d1-ba6b-45f1-9f80-7d57005eabe7-0693 (Jenkins Scheduler) at scheduler-60588491-ed72-4166-82e1-2755ab6ae164@96.119.2.253:59256 disconnected
