### ISSUE TITLE
Mesos slaves filling up /var/lib/jenkins/logs/slaves/

### ISSUE THREAD

**Issue by ktf** [jenkinsci/mesos-plugin#86]
Looks like mesos slaves never delete their folder in:

/var/lib/jenkins/logs/slaves/

in the long run this causes issues because you eventually reach the max inodes per folder limit.

Is this expected?

**Comment by daniel-beck** [comment]
FWIW ext4 does not have the 32k inode limit per directory.

**Comment by vinodkone** [comment]
What are log files located in this directory? Is that created by Jenkins slave(s)?

**Comment by damomurf** [comment]
I'm seeing this too - the static (non-mesos) slaves in the same directory have a slave.log file which contains a dump of the environment and then the slave logs as visible in the UI.

In my case, the 11,500 (!) mesos-jenkins-* directories seem to be all empty.

I'm not sure if this output in Jenkins own log is related, but it certainly looks like it could be:

```
Jul 03, 2016 3:55:06 AM hudson.slaves.SlaveComputer kill
WARNING: Unable to delete slave logs
java.nio.file.DirectoryNotEmptyException: /var/lib/jenkins/logs/slaves/mesos-jenkins-46d44420a791422b99e624221fcffb3a-mesos-java8
        at sun.nio.fs.UnixFileSystemProvider.implDelete(UnixFileSystemProvider.java:242)
        at sun.nio.fs.AbstractFileSystemProvider.delete(AbstractFileSystemProvider.java:103)
        at java.nio.file.Files.delete(Files.java:1126)
        at sun.reflect.GeneratedMethodAccessor5484.invoke(Unknown Source)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:498)
        at hudson.Util.deleteFile(Util.java:257)
        at hudson.Util.deleteRecursive(Util.java:320)
        at hudson.slaves.SlaveComputer.kill(SlaveComputer.java:670)
        at hudson.model.AbstractCIBase.killComputer(AbstractCIBase.java:86)
        at hudson.model.AbstractCIBase.updateComputerList(AbstractCIBase.java:205)
        at jenkins.model.Jenkins.updateComputerList(Jenkins.java:1260)
        at jenkins.model.Nodes$4.run(Nodes.java:219)
        at hudson.model.Queue._withLock(Queue.java:1306)
        at hudson.model.Queue.withLock(Queue.java:1189)
        at jenkins.model.Nodes.removeNode(Nodes.java:210)
        at jenkins.model.Jenkins.removeNode(Jenkins.java:1760)
        at org.jenkinsci.plugins.mesos.MesosSlave.terminate(MesosSlave.java:101)
        at org.jenkinsci.plugins.mesos.MesosCleanupThread$1.run(MesosCleanupThread.java:98)
        at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at jenkins.util.ContextResettingExecutorService$1.run(ContextResettingExecutorService.java:28)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by jeschkies** [comment]
@ktf, are you still seeing this issue?

**Comment by jeschkies** [comment]
Closing for lack of response.
